import { Geist, Geist_Mono } from 'next/font/google';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import './globals.css';
import Navbar from './components/Navbar';
import Footer from './components/Footer';
import Playground from './components/Playground';
// import dynamic from 'next/dynamic';

// const Playground = dynamic(() => import('./components/Playground'), {
//   loading: <div>This is loading data</div>,
//   ssr: false,
// });

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'My portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        {/* <Playground /> */}
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
